nama=input("silahkan masukan nama anda = ")
umur=int(input("Masukan umur = "))
alamat=input("Masukan alamat = ")
lulusan=input("Lulusan sekolah = ")
agama=input("Agama = ")
nim=input("Nim = ")
tgl=input("Tgl = ")

print("=="*20)
print("   {BIODATA MAHASISWA STMIK,LOMBOK}") 
print("    -------------------------------")
print("|   NAMA      :", nama    )
print("|   NIM       :", nim     )
print("|   UMUR      :", umur    )
print("|   TGL LAHIR :", tgl    )
print("|   ALAMAT    :", alamat  )
print("|   AGAMA     :", agama   )
print("|   LULUSAN   :", lulusan )
print("=="*20)
