nama=("Ikhwan Maulana Ivansyah")
umur=int(("18"))
alamat=("Ganti, Praya Timur")
lulusan=("MAN 1 LOMBOK TENGAH")
agama=("Islam")
nim=("SI20230016")
tgl=("13 Juni 2005")
nomor=int(("+6282340824547"))
email=("elyaivanmey@gamil.com")

print("=="*20)
print("   {BIODATA MAHASISWA STMIK LOMBOK}") 
print("    -------------------------------")
print("|   NAMA      :", nama    )
print("|   NIM       :", nim     )
print("|   UMUR      :", umur    )
print("|   TGL LAHIR :", tgl    )
print("|   ALAMAT    :", alamat  )
print("|   AGAMA     :", agama   )
print("|   LULUSAN   :", lulusan )
print("    -------------------------------")
print("    {KONTAK MAHASISWA STMIK LOMBOK}") 
print("    -------------------------------")
print("|   NOMOR     :", nomor )
print("|   E-MAIL    :", email)
print("=="*20)
